Webanck demo bron
VCityTeam/UD-Viz pull request #266
Opened 2021-12-03 13:27 UTC by valentinMachado

2021-12-07 10:43 UTC, webanck commented
@valentinMachado is there anything preventing from accepting this PR ?

2021-12-08 16:22 UTC, mathieuLivebardon requested changes

2021-12-08 16:22 UTC, mathieuLivebardon commented on examples/assets/localScripts/localAvatar.js
> +    /*
Remove commented code

2021-12-08 16:22 UTC, mathieuLivebardon commented on examples/assets/localScripts/localAvatar.js
> +    //if(!intersections.length) debugger;
remove comments

2021-12-08 16:22 UTC, mathieuLivebardon commented on examples/assets/localScripts/localAvatar.js
> +    // const pos = this.avatar.getPosition();
remove comments

2021-12-08 16:22 UTC, mathieuLivebardon commented on examples/assets/localScripts/localAvatar.js
> +    // const gV = localContext.getGameView();
remove comments

2022-01-12 17:33 UTC, merged