Create an example of a multi player game #492
VCityTeam/UD-Viz pull request #513
Opened 2023-02-01 15:39 UTC by valentinMachado

2023-02-10 16:51 UTC, valentinMachado commented on packages/node/package.json
> +    "debug": "nodemon --trace-warnings --verbose --watch src --delay 2500ms ./examples/example1.js -e js,css,html"
should be remove

2023-02-10 16:51 UTC, valentinMachado commented on packages/node/package.json
> +    "express": "^4.18.2",
express is declare twice

2023-02-17 15:25 UTC, mathieuLivebardon requested changes
There are ui problems when i tried to test the example.
When i press 'n' the `div`which display is placed at the top left of the screen.
![image](https://user-images.githubusercontent.com/34244904/219695085-06bf51c5-627d-4f78-9c40-455e9c1b07da.png)

2023-02-17 15:25 UTC, mathieuLivebardon commented on packages/node/src/Game/SocketWrapper.js
> +module.exports = class SocketWrapper {
doc 👀

2023-02-17 15:25 UTC, mathieuLivebardon commented on packages/node/src/Game/Thread.js
> +const Thread = class {
doc 👀

2023-02-17 15:25 UTC, mathieuLivebardon commented on packages/shared/src/Game/Object3D.js
> +    /** @type {object} - user data */
this.userData is explicit

2023-02-17 15:25 UTC, mathieuLivebardon commented on packages/shared/src/Game/ScriptTemplate/NativeCommandManager.js
> + * Manage native command
@class

2023-02-20 14:03 UTC, valentinMachado commented
> There are ui problems when i tried to test the example. When i press 'n' the `div`which display is placed at the top left of the screen. ![image](https://user-images.githubusercontent.com/34244904/219695085-06bf51c5-627d-4f78-9c40-455e9c1b07da.png)

the note is supposed to be on top of your mouse when it hovers the 3D view. is it happening whatever where you place your mouse ? (I don't reproduce this behavior here). Note that if your note is close from the side bar then this latter will overlap the menu edit note. I just implement a feature which allow to move with the itowns controller 3D view even if there is a menu edit instanced, so the user can move the camera to make the menu edit note available if it was hidding

2023-02-20 14:35 UTC, valentinMachado commented on packages/browser/src/Component/ExternalGame/Context.js
>     * @todo need refacto
i rename it since this function is going to be use in IMUV

2023-02-20 14:35 UTC, valentinMachado commented on packages/browser/src/Component/ExternalGame/ScriptTemplate/CameraManager.js
> +    /** @type {Target|null} - target object3D */
fixed

2023-02-21 10:27 UTC, mathieuLivebardon approved these changes
Works in chrome.

2023-02-21 10:30 UTC, merged