Remove 3dtiles layer by ID
VCityTeam/UD-Viz pull request #541
Opened 2023-03-01 16:00 UTC by clementcolin

2023-03-01 16:37 UTC, valentinMachado requested changes
Same comment as https://github.com/VCityTeam/UD-Viz/pull/542

2023-03-01 16:37 UTC, valentinMachado commented on packages/browser/src/Component/Itowns/LayerManager/LayerManager.js
> +   * @returns {TilesManager}
this function return nothing

2023-03-08 14:25 UTC, clementcolin commented
Should be good now :)

2023-03-08 14:49 UTC, valentinMachado commented
eslint doesnt pass in index.js ^^ but everything seems fine to me

2023-03-13 12:47 UTC, merged