Make an ud viz splashscreen #479
VCityTeam/UD-Viz pull request #655
Opened 2023-05-11 13:24 UTC by valentinMachado

Since this code is more or less only css it was pointless to add it in source since we want to get rid of the css in src. So I add it in asset/js of the example as a script that could reuse for all example, for now it's just implemented in the sidebarwidget example though.

2023-05-17 12:32 UTC, LorenzoMarnat approved these changes
Looks really good

Do you know when the LAYERS_INITIALIZED is dispatched ? Do we have to wait until the 3DTiles are fully loaded ?

2023-05-17 12:34 UTC, mathieuLivebardon requested changes

2023-05-17 13:58 UTC, valentinMachado commented
> Do you know when the LAYERS_INITIALIZED is dispatched ? Do we have to wait until the 3DTiles are fully loaded ?

[This](https://github.com/iTowns/itowns/blob/a8dfb36cb6c86d0e5a9a9db41f8fb9feb9a7e9ab/src/Core/View.js#L203) is a function call at the `UPDATE_END` event of the main loop. When all `layer.ready = true` the event is dispatched. The `.ready` fields of each layer is set to true when the `whenReady` promise is fullfill [see](https://github.com/iTowns/itowns/blob/a8dfb36cb6c86d0e5a9a9db41f8fb9feb9a7e9ab/src/Layer/Layer.js#L133).
This promise is fullfil when all `._promises` of the layer are fullfill [see](https://github.com/iTowns/itowns/blob/a8dfb36cb6c86d0e5a9a9db41f8fb9feb9a7e9ab/src/Core/View.js#L354).
You can add asynchronous initialization step to a layer [see](https://github.com/iTowns/itowns/blob/a8dfb36cb6c86d0e5a9a9db41f8fb9feb9a7e9ab/src/Layer/Layer.js#L152) which basically add promise to `_promises`.
In the case of the C3DTilesLayer one initialization step is added which is the tileset.json fetch [see](https://github.com/iTowns/itowns/blob/a8dfb36cb6c86d0e5a9a9db41f8fb9feb9a7e9ab/src/Layer/C3DTilesLayer.js#LL101C1-L101C1). So when this event is dispatched for C3DTilesLayer this means that the tileset.json has been fetched no more.

2023-05-17 14:32 UTC, valentinMachado commented on examples/assets/js/loadingScreen.js
> +      setTimeout(() => root.remove(), 1000); // <-- hard coded because root.style.transitionDuration is empty ??
done that's working now don't know why it was not before

2023-05-22 14:50 UTC, mathieuLivebardon approved these changes

2023-05-22 14:50 UTC, merged