Add example in ud-viz using maptastic
VCityTeam/UD-Viz pull request #736
Opened 2023-09-14 14:35 UTC by mathieuLivebardon

A first use of maptastic has been realized as part of the [UD_Reagent_ABM] project (https://github.com/VCityTeam/UD_ReAgent_ABM). 
This PR adds an example and some code to the examples/ folder.

2023-09-26 12:33 UTC, valentinMachado commented
This is working fine can you add some doc to indicate to the user how to use maptastic (at least shift + space to activate)

> I rebase your branch to update it with ud-viz 4.0.0 and thus `git push --force` think to delete your local branch before to pull

2023-10-20 13:24 UTC, LorenzoMarnat reviewed
Some problems about controls:

- If you enable edit mode (Shift+ space), it also triggers iTowns 'space' event (zoom on the map)
- Once in edit mode, pressing 's' also hides the slideshow UI
- Once in edit mode, pressing 'h' also hides the slideshow

Also, the mosaic image of the mapastic example is the same as '3dtiles layer style'

2023-10-20 13:27 UTC, LorenzoMarnat requested changes

2023-10-20 13:27 UTC, LorenzoMarnat commented on index.html
> +        './examples/assets/img/mosaic/C3DTilesLayerStyle.png'
Change mosaic image

2023-10-25 11:47 UTC, LorenzoMarnat approved these changes

2023-10-25 13:09 UTC, merged