Graph clustering
VCityTeam/UD-Viz pull request #823
Opened 2024-07-10 12:07 UTC by Manon3005

2024-08-22 11:36 UTC, DiegoVinasco commented
@Manon3005 would also like to add #835 to this PR if possible

2024-08-27 11:31 UTC, DiegoVinasco commented on examples/assets/config/layer/3DTiles_point_cloud.json
I don't even understand how we were able to parse this file before with a syntax error like that

2024-08-27 12:05 UTC, DiegoVinasco requested changes
The PR is in good shape. There's just a few things that need to be modified before the PR is accepted, please see my comments.

Once those are done we should follow the [PR submission checklist](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/Contributing.md#submiting-pull-request-pr) to make sure everything is ready. Then we can merge the PR!

- [x] Comments
- [ ] [Checklist](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/Contributing.md#submiting-pull-request-pr)
- [ ] PR/MR

2024-08-27 14:07 UTC, Manon3005 commented on packages/widget_sparql/src/view/D3GraphCanvas.js
> +      const getNormalVec = (A, B) => {
Docstring added!

2024-08-27 14:08 UTC, Manon3005 commented on examples/assets/config/layer/3DTiles_temporal.json
Changes made!

2024-08-27 15:06 UTC, DiegoVinasco approved these changes

2024-08-28 08:50 UTC, merged